# Generated by Django 4.2.18 on 2025-02-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0002_uploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to='files'),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
